# Variables
* Variable name must start with a letter or the underscore character
* Variable name cannot start with a number
* Variable name can only contain: alphanumeric characters (A-z, 0-9) or underscores ( _ )
* Variable names are case sensitive

In [1]:
x = 5
_y = "hello world"

print(x)
print(_y)
x = "ece196"
print(x)

5
hello world
ece196


# Comments
* Inline comment with the pound ( # ) key
* Multiple-line comment with triple quotes ( ‘’’ or “”” )

In [2]:
# This is an inline command
x = 5
y = "hello world"

'''
    This is a multi-line comment
    It can use as many line as necessay
'''
print(x)
print(y)

"""
    Multi-line comment alse used via
    either single quotes, or double quotes
"""
x = "ece196"
print(x)

5
hello world
ece196


# Math
* Three types of number in Python: **int**, **float**, and **complex**
* 4 possible operations: addition ( **+** ), subtraction ( **-** ), multiplication ( ***** ), division ( **/** )


In [3]:
x = 5
print(type(x))

y = 10.0
print(type(y))
z = x + y
print(z, type(z))

z = 5 + 10j
print(z, z.real, z.imag)

<class 'int'>
<class 'float'>
15.0 <class 'float'>
(5+10j) 5.0 10.0


# Conditionals
**if** condition 1:

    code goes here
    
**elif** condition 2:

    code goes here

**else:**

    code goes here

In [4]:
x = 10
y = 5.0
z = 15.0
if x < 10:
    print("x is less than 15")
elif x >= 10 and y == 5:
    print("x is greater than or equal to 10 and y is equal to 5")
else:
    print("else statement")

x is greater than or equal to 10 and y is equal to 5


# List
Refer to the following [link](https://docs.python.org/3/tutorial/datastructures.html) for all the available function. 

In [5]:
my_grocery_list = ["bananas", "apples", "tomatoes"] # create a list of groceries
print(my_grocery_list)

my_grocery_list.append("cookies") # add "cookies" at the end of the gorcery list
print("after appending cookies: ", my_grocery_list)

my_grocery_list.pop() # remove the last item in the grocery list
print(my_grocery_list)

my_grocery_list.insert(2, "oranges") # add "oranges" after the second item in the list
print(my_grocery_list)

my_grocery_list[1] = "gala apples"   # change the second item in my list to "gala apples"
print(my_grocery_list)

['bananas', 'apples', 'tomatoes']
after appending cookies:  ['bananas', 'apples', 'tomatoes', 'cookies']
['bananas', 'apples', 'tomatoes']
['bananas', 'apples', 'oranges', 'tomatoes']
['bananas', 'gala apples', 'oranges', 'tomatoes']


# Tuples
Tuples works similar to list, except tuples are immutable. Refer to the following [link](https://www.tutorialspoint.com/python/python_tuples.htm) for all the available function. 

In [6]:
my_grocery_list = ("bananas", "apples", "tomatoes")  # create a tuple of groceries
print(my_grocery_list)

# my_grocery_list.append("cookies")   # this would throw an error
# my_grocery_list.pop()               # this would throw an error
# my_grocery_list[1] = "gala apples"  # this would throw an error

# a way to modify tuple is to create another tuple and concatenate the tuple
another_grocery_list = ("cookies", "potatoes")
my_grocery_list = my_grocery_list + another_grocery_list
print(my_grocery_list)

('bananas', 'apples', 'tomatoes')
('bananas', 'apples', 'tomatoes', 'cookies', 'potatoes')


# Loops
## for loops
**for** *var* in *sequence*:

    code goes here

In [7]:
for i in my_grocery_list:
    print(i)

bananas
apples
tomatoes
cookies
potatoes


## while loops
**while** stopping_condition:
    
    code goes goes
    
**Python does not support do-while loops**

In [8]:
i = len(my_grocery_list) - 1
while i >= 0:
    print(my_grocery_list[i])
    i -= 1

potatoes
cookies
tomatoes
apples
bananas


# Range
Refer to the following [link](https://docs.python.org/3/library/functions.html#func-range) for further reference.

In [9]:
for i in range(10):           # provide an ending point
    print("i = ", i)

for j in range(1, 10):        # provide a starting and ending point
    print("j = ", j)
    
for k in range(2, 20, 2):     # provide a starting point, ending point, and step
    print("k = ", k)

i =  0
i =  1
i =  2
i =  3
i =  4
i =  5
i =  6
i =  7
i =  8
i =  9
j =  1
j =  2
j =  3
j =  4
j =  5
j =  6
j =  7
j =  8
j =  9
k =  2
k =  4
k =  6
k =  8
k =  10
k =  12
k =  14
k =  16
k =  18


# Dictionary
Dictionaries are comma separated key-value pairs. Refer to the following [link](https://www.w3schools.com/python/python_dictionaries.asp) for further reference.

In [10]:
# Creating Dictionary
workout_dictionary = {"Mon": ["Push-up", "situps", "squads"],
                      "Tue": "Run 3 miles",
                      "Wed": "Rest",
                      "Th": ["Push-up", "situps", "squads"],
                      "Fri": "Run 3 miles"
                     }
print(workout_dictionary["Th"])   # Accessing Items
workout_dictionary["Fri"] = ["Push-up", "situps", "squada", "run 3 miles"]    # Modifying Items
print(workout_dictionary["Fri"])
workout_dictionary["Sat"] = "Rest"   # Adding Items
print(workout_dictionary)

['Push-up', 'situps', 'squads']
['Push-up', 'situps', 'squada', 'run 3 miles']
{'Mon': ['Push-up', 'situps', 'squads'], 'Tue': 'Run 3 miles', 'Wed': 'Rest', 'Th': ['Push-up', 'situps', 'squads'], 'Fri': ['Push-up', 'situps', 'squada', 'run 3 miles'], 'Sat': 'Rest'}


# Functions
**def** *functionName*( _parameters_ ):

    code goes here

In [11]:
def printMe( str = "Hello World" ):   # function with default parameter
    print( str )
        

def printMyAndMe( str1, str2 = "Hello World" ):  # function with and without default parameter
    print("str = ", str1)
    print("str2 = ", str2)
    
def addOne(x):  # function with return variable
    return x + 1

def addOneAndTwo(x):  # function with more than one return variable
    return x + 1, x + 2

printMe()
printMe( 5 )

printMyAndMe("ECE", 196)

print( addOne(5) )
print( addOneAndTwo(5) )  # Notice the return type of this function

Hello World
5
str =  ECE
str2 =  196
6
(6, 7)


# Classes
For a detail explanation of classes in Python, refer to the offical [documentation](https://docs.python.org/3/tutorial/classes.html).

**class** ClassName:
    
    <statement-1>
    .
    .
    .
    <statement-N>

In [12]:
class MyClass:
    """A simple example class"""
    i = 12345

    def f(self):
        return 'hello world'
    
x = MyClass()
print( x )
print( x.i )
print( x.f() )

12345
hello world


# Modules
For a detail explanation of modules in Python, refer to the official [documentation](https://docs.python.org/3/tutorial/modules.html).

In [13]:
import numpy  # numpy module cheat sheet (not comprehensive): https://www.dataquest.io/blog/numpy-cheat-sheet/ 

x = numpy.array([1,2,3,4,5])
print(x)
y = numpy.array([2,3,4,5,6])
print(y)
print(x + y)

import numpy as np  # assigning a alias to module

array = np.array([[1,2,3], [4, 5, 6]])
print("array = \n", array)

print("Printing one row at a time:")
for rows in array:
    print(rows)
    
print("Printing one elemtn at a time:")
for rows in array:
    for col in rows:
        print(col)

[1 2 3 4 5]
[2 3 4 5 6]
[ 3  5  7  9 11]
array = 
 [[1 2 3]
 [4 5 6]]
Printing one row at a time:
[1 2 3]
[4 5 6]
Printing one elemtn at a time:
1
2
3
4
5
6
